In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
%run -i "utils.py"

# Load the dataset

In [3]:
df = pd.read_csv(
    'https://github.com/clairett/pytorch-sentiment-classification/raw/master/data/SST2/train.tsv',
    delimiter='\t',
    header=None
)

In [4]:
df.shape

(6920, 2)

In [5]:
df.head()

                                                   0  1
0  a stirring , funny and finally transporting re...  1
1  apparently reassembled from the cutting room f...  0
2  they presume their audience wo n't sit still f...  0
3  this is a visually stunning rumination on love...  1
4  jonathan parker 's bartleby should have been t...  1

In [6]:
# rename the columns for Hugging Face classification task
df.rename(
    columns={
        0: "text",
        1: "label"
    },
    inplace= True
)

In [7]:
df.head()

                                                text  label
0  a stirring , funny and finally transporting re...      1
1  apparently reassembled from the cutting room f...      0
2  they presume their audience wo n't sit still f...      0
3  this is a visually stunning rumination on love...      1
4  jonathan parker 's bartleby should have been t...      1

In [8]:
df["label"].value_counts(normalize= True)

label
1    0.521676
0    0.478324
Name: proportion, dtype: float64

# Load pretrained model/tokenizer

In [9]:
# Instantiate the sentiment trainer class and
# load pretrained DistilBERT model/tokenizer
st = HuggingFaceSentimentTrainer(
    model_name="distilbert-base-uncased",
    num_labels=2
)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [10]:
st.model_name

'distilbert-base-uncased'

In [11]:
st.tokenizer

DistilBertTokenizerFast(name_or_path='distilbert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [12]:
st.model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [13]:
st.tokenizer.decode(
    st.tokenizer(df.iloc[0,0])["input_ids"]
)

'[CLS] a stirring, funny and finally transporting re imagining of beauty and the beast and 1930s horror films [SEP]'

In [14]:
st.tokenizer.decode(
    st.tokenizer("hey!, Let's fine-tune the DistilBERT model ;)")["input_ids"]
)

"[CLS] hey!, let's fine - tune the distilbert model ; ) [SEP]"

## Preparing data for Trainer

In [15]:
st.preprare_input_for_trainer(df, test_size=.4)

Training Set: 4,152 samples
Validation Set: 1,384 samples
Test Set: 1,384 samples

## Train the model (fine tuning)

In [16]:
st.train_model()

 34%|███▍      | 264/780 [00:14<01:05,  7.87it/s]

{'eval_loss': 0.2791818380355835, 'eval_runtime': 1.1269, 'eval_samples_per_second': 1228.131, 'eval_steps_per_second': 77.202, 'epoch': 1.0}

 64%|██████▍   | 500/780 [00:25<00:13, 20.70it/s]

{'loss': 0.2886, 'grad_norm': 17.94817352294922, 'learning_rate': 1.794871794871795e-05, 'epoch': 1.92}

 67%|██████▋   | 523/780 [00:29<00:45,  5.69it/s]

{'eval_loss': 0.3348124921321869, 'eval_runtime': 1.1284, 'eval_samples_per_second': 1226.469, 'eval_steps_per_second': 77.097, 'epoch': 2.0}

100%|██████████| 780/780 [00:45<00:00, 17.27it/s]

{'eval_loss': 0.4733659029006958, 'eval_runtime': 1.1336, 'eval_samples_per_second': 1220.836, 'eval_steps_per_second': 76.743, 'epoch': 3.0}
{'train_runtime': 45.1693, 'train_samples_per_second': 275.763, 'train_steps_per_second': 17.268, 'train_loss': 0.20661069185305864, 'epoch': 3.0}

100%|██████████| 87/87 [00:01<00:00, 77.42it/s]

model's performance on a validation dataset: {'eval_loss': 0.4733659029006958, 'eval_runtime': 1.1326, 'eval_samples_per_second': 1222.004, 'eval_steps_per_second': 76.817, 'epoch': 3.0}

## Model performance on the test set

In [ ]:
st.compute_metrics()

100%|██████████| 87/87 [00:01<00:00, 79.57it/s]

      metric     value
0   Accuracy  0.895954
1  Precision  0.888430
2     Recall  0.911017
3   F1 Score  0.899582